### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by ap1969** [huangcheng/craft-extension-mermaid#2]
Hi, 
I'm just switching from Notion to Craft, and one thing I'd like is MermaidJS functionality.

I've installed your plugin - I can see it in the extensions list, but how do I actually use it? I've tried adding a code block, but can't see any way to set the language to Mermaid.

I'm using the Windows app - not sure if that makes a difference?

Regards,
Andy

**Comment by huangcheng** [comment]
HI,
The plugin has been successfully tested in the latest version of Craft for Windows, and it still works perfectly. 

The code block can be rendered by simply selecting it with your cursor and clicking on the button right next to it. This is because Craft has made changes to their code editor, and this might be the easiest way to select the whole code block.

![image](https://github.com/huangcheng/craft-extension-mermaid/assets/2804393/d7ce9f18-32b6-4858-a227-7c5cfa56e04d)

![image](https://github.com/huangcheng/craft-extension-mermaid/assets/2804393/d3998977-6e5d-4846-bd40-be9dafae905d)
